### ISSUE TITLE
Feedback on prefix trees

### ISSUE THREAD

**Issue by Anisha7** [Mintri1199/CS-2.1-Trees-Sorting#2]
Great job on completing the prefix tree! 

- Your get_child gets an index error. Are you checking if its a valid index before accessing that index? Remember, lists throw an index error if you provide an out-of-bounds integer.
- Your complete and strings methods are also failing tests. Use print statements to try and figure out what is going on in your code. Looks like you have some commented code for _traverse which works! Uncomment this code so your strings tests pass!
- You can further challenge yourself by working on time and space complexities for each prefix tree method. You would be expected to do this in interviews, and it would be good practice :)

**Comment by Mintri1199** [comment]
@Anisha7 Hi I forgot to tell you that there file version you've reviewed was messed up. I've modified some of the test since I started the prefix tree earlier than the rest of the class. So I asked Alan permission to modified the test while including all the behaviors of his version of the prefix tree since I didn't want to waste my effort building out another prefix tree to accommodate the class.
